### PR TITLE
Added axios request for project/id api

### PR DESCRIPTION
**Pull request by amvaid**
@maikoo can Review this. I just created an axios request for my project endpoint.

### CODE REVIEW

**Review by maikoo — CHANGES_REQUESTED** [review]
Can you also include a catch for errors? I understand that this may work fine but best to handle all promise based errors just in case.

**Comment by amvaid** [comment]
@maikoo Just added the catch for error. Thanks for pointing it out!

**Comment by amvaid** [comment]
@maikoo updated error catch.

**Review by maikoo — APPROVED** [review]
This looks much better. One thing I anticipate that you may have to change is the setting of state as you may need to have multiple keys to hold different data in the future perhaps.

**Pull request merged**
