### PR TITLE
Database configuration

### PR DESCRIPTION
**Pull request by amvaid**
@zcoursey22 I decided to go with mysql instead of MongoDB and mongoose. Can you review my changes?

### CODE REVIEW

**Review by zcoursey22 — COMMENTED** [review]
Did you check to make sure your database is created in the terminal?

**Comment by amvaid** [comment]
@zcoursey22 yup! I ran the mysql -u root < schema.sql command

**Review by zcoursey22 — APPROVED** [review]
For organization, consider moving your schema into your db folder.

**Comment by amvaid** [comment]
thanks I'll look into it

**Pull request merged**
