### PR TITLE
Title description

### PR DESCRIPTION
**Pull request by amvaid**
@maikoo I created my title component and made some change to my styled-components for the creator.

### CODE REVIEW

**Review by maikoo — CHANGES_REQUESTED** [review]
Instead of using the font family multiple times, you could create a styled component on your main app.jsx that applies it 'globally'. Seems cleaner that way and wouldn't have to worry if that makes sense.

**Comment by amvaid** [comment]
@maikoo I made the changes you suggested.

**Review by maikoo — APPROVED** [review]
This looks better! I think it'll be helpful moving forward when you have to use the font again.

**Comment by amvaid** [comment]
@maikoo I agree. Great Idea!

**Pull request merged**
